//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by pet_toolset.rc
//
#define IDD_MAIN_WINDOW                 101
#define IDD_PE_VIEWER_WINDOW            103
#define IDD_SECTION_WINDOW              105
#define IDD_DIRECTORY_WINDOW            107
#define IDC_MAIN_MODULE_LIST            1006
#define IDC_MAIN_PROCESS_LIST           1007
#define IDC_MAIN_DLL_INJECTION_BTN      1008
#define IDC_MAIN_EXE_PACK_BTN           1009
#define IDC_PE_VIEWER_MACHINE_NUMBER    1009
#define IDC_MAIN_PROCESS_VIEWER_BTN     1010
#define IDC_EDIT2                       1010
#define IDC_MAIN_ABOUT_BTN              1011
#define IDC_PE_VIEWER_TIMESTAMP         1011
#define IDC_MAIN_EXIT_BTN               1012
#define IDC_PE_VIEWER_OH_SIZE           1012
#define IDC_PE_VIEWER_ENTRY_POINT       1013
#define IDC_PE_VIEWER_SECTION_ALIGNMENT 1014
#define IDC_PE_VIEWER_IMAGE_SIZE        1015
#define IDC_PE_VIEWER_CHECKSUM          1016
#define IDC_PE_VIEWER_EXIT_BUTTON       1017
#define IDC_SECTION_LIST                1019
#define IDC_SECTION_CLOSE_BTN           1020
#define IDC_DIRECTORY_EXIT_BTN          1021
#define IDC_DIRECTORY_EXPORT_TABLE_RVA  1022
#define IDC_DIRECTORY_EXPORT_TABLE_SIZE 1023
#define IDC_DIRECTORY_IMPORT_TABLE_RVA  1024
#define IDC_DIRECTORY_IMPORT_TABLE_SIZE 1025
#define IDC_DIRECTORY_RESOURCE_TABLE_RVA 1026
#define IDC_DIRECTORY_RESOURCE_TABLE_SIZE 1027
#define IDC_DIRECTORY_EXCEPTION_TABLE_RVA 1030
#define IDC_DIRECTORY_EXCEPTION_TABLE_SIZE 1031
#define IDC_DIRECTORY_SECURITY_TABLE_RVA 1034
#define IDC_DIRECTORY_SECURITY_TABLE_SIZE 1035
#define IDC_DIRECTORY_BASE_RELOCATION_TABLE_RVA 1036
#define IDC_DIRECTORY_BASE_RELOCATION_TABLE_SIZE 1037
#define IDC_DIRECTORY_DEBUG_TABLE_RVA   1038
#define IDC_DIRECTORY_DEBUG_TABLE_SIZE  1039
#define IDC_PE_VIEWER_PE_HEADER_OFFSET  1040
#define IDC_PE_VIEWER_NUMBER_OF_SECTIONS 1041
#define IDC_PE_VIEWER_CHARACTERISTICS   1042
#define IDC_DIRECTORY_ASD_TABLE_RVA     1042
#define IDC_PE_VIEWER_IMAGE_BASE        1043
#define IDC_DIRECTORY_ASD_TABLE_SIZE    1043
#define IDC_PE_VIEWER_FILE_ALIGNMENT    1044
#define IDC_PE_VIEWER_HEADER_SIZE       1045
#define IDC_PE_VIEWER_DLL_CHARACTERISTICS 1046
#define IDC_PE_VIEWER_DATA_DIR_BUTTON   1050
#define IDC_DIRECTORY_GPR_TABLE_RVA     1050
#define IDC_PE_VIEWER_SECTION_BUTTON    1051
#define IDC_DIRECTORY_GPR_TABLE_SIZE    1051
#define IDC_DIRECTORY_TLS_TABLE_RVA     1052
#define IDC_DIRECTORY_TLS_TABLE_SIZE    1053
#define IDC_DIRECTORY_LCT_TABLE_RVA     1066
#define IDC_DIRECTORY_LCT_TABLE_SIZE    1067
#define IDC_DIRECTORY_BIT_TABLE_RVA     1068
#define IDC_DIRECTORY_BIT_TABLE_SIZE    1069
#define IDC_DIRECTORY_IAT_TABLE_RVA     1070
#define IDC_DIRECTORY_IAT_TABLE_SIZE    1071
#define IDC_DIRECTORY_DELAY_IMPORT_TABLE_RVA 1072
#define IDC_DIRECTORY_DEALY_IMPORT_TABLE_SIZE 1073
#define IDC_DIRECTORY_DELAY_IMPORT_TABLE_SIZE 1073
#define IDC_DIRECTORY_CLR_TABLE_RVA     1076
#define IDC_DIRECTORY_CLR_TABLE_SIZE    1077
#define IDC_DIRECTORY_RESERVED_TABLE_RVA 1078
#define IDC_DIRECTORY_RESERVED_TABLE_SIZE 1079

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        109
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1023
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
